### PR TITLE
SAML provider for TIB

### PR DESCRIPTION
**Pull request by joshblakeley**
Fixes https://github.com/TykTechnologies/tyk-identity-broker/issues/7

Docs PR here: https://github.com/TykTechnologies/tyk-docs/pull/1256

- Tested with AzureAD and samltest.id

- [x]  Redirect 
- [x] POST
- [x] Claim mapping
- [x] docs

Docs: 

**SSO with SAML and Tyk**

SAML authentication is a way for a service provider, such as the Tyk Dashboard or Portal, to assert the Identity of a User via a third party.

Tyk Identity Broker can act as the go-between for the Tyk Dashboard and Portal and a third party identity provider. Tyk Identity broker can also interpret and pass along information about the user who is logging in such as Name, Email and group or role metadata for enforcing role based access control in the Tyk Dashboard.

The provider config for SAML has the following values that can be configured in a Profile:

`SAMLBaseURL` - The host of TIB that will be used in the metadata document for the Service Provider. This will form part of the metadata URL used as the Entity ID by the IDP. The redirects configured in the IDP must match the expected Host and URI configured in the metadata document made available by Tyk Identity Broker.

`FailureRedirect` - Where to redirect failed login requests.

`IDPMetaDataURL` - The metadata URL of your IDP which will provide Tyk Identity Broker with information about the IDP such as EntityID, Endpoints (Single Sign On Service Endpoint, Single Logout Service Endpoint), its public X.509 cert, NameId Format, Organization info and Contact info.

This metadata XML can be signed providing a public X.509 cert and the private key.     

`CertFile` - An X.509 certificate for signing your requests to the IDP

 'KeyFile' - A private key for signing your requests to the IDP

`ForceAuthentication` - Ignore any session held by the IDP and force re-login every request.

`SAMLEmailClaim` - Key for looking up the email claim in the SAML assertion form the IDP. Defaults to: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress`

`SAMLForenameClaim` - Key for looking up the forename claim in the SAML assertion form the IDP. Defaults to: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/forename`

`SAMLSurnameClaim` - Key for looking up the surname claim in the SAML assertion form the IDP. Defaults to: `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname`

Example profile configuration:

```
{
    "ActionType": "GenerateOrLoginUserProfile",
    "ID": "saml-sso-login",
    "OrgID": "{YOUR_ORGANISATION_ID}",
    "CustomEmailField": "",
    "IdentityHandlerConfig": {
        "DashboardCredential": "{DASHBOARD_USER_API_KEY}"
    },
    "ProviderConfig": {
        "SAMLBaseURL": "https://{HOST}",
        "FailureRedirect": "http://{DASHBOARD_HOST}:{PORT}/?fail=true",
        "IDPMetaDataURL": "{IDP_METADATA_URL}",
        "CertFile":"myservice.cert",
        "KeyFile": "myservice.key",
        "ForceAuthentication": false,
        "SAMLEmailClaim": "",
        "SAMLForenameClaim": "",
        "SAMLSurnameClaim": ""
    },
    "ProviderName": "SAMLProvider",
    "ReturnURL": "http://{DASHBOARD_URL}:{PORT}/tap",
    "Type": "redirect"
}
```

### CODE REVIEW

File: providers/saml.go [hunk 1]
```diff
@@ -0,0 +1,299 @@
...
+	SAMLBinding         string
+	SAMLEmailClaim      string
+	SAMLForenameClaim   string
+	SAMLSurnameClaim    string
+	FailureRedirect     string
+}
+
+func (s *SAMLProvider) Init(handler tap.IdentityHandler, profile tap.Profile, config []byte) error {
+	//if an external logger was set, then lets reload it to inherit those configs
+	onceReloadADLogger.Do(func() {
```
Comment (sredxny) [inline providers/saml.go:54]: here we must user onceReloadSAMLLogger

File: providers/saml.go [hunk 2]
```diff
@@ -0,0 +1,299 @@
...
+}
+
+func (s *SAMLProvider) initialiseSAMLMiddleware() {
+	if middleware == nil {
+
+		SAMLLogger.Debug("Initialising middleware SAML")
+		//needs to match the signing cert if IDP
+		keyPair, err := tls.LoadX509KeyPair(s.config.CertFile, s.config.KeyFile)
+		if err != nil {
+			log.Errorf("Error loading keypair: %v", err)
```
Comment (sredxny) [inline providers/saml.go:91]: Use SAMLLogger

**Comment by joshblakeley** [comment]
@sredxny @buger Docs are made.

I'll open docs PR to copy relevant info across. I also will update TIB readme with new info too.

**Comment by bmonteiro** [comment]
@joshblakeley @letzya it is possible for you guys to push a release candidate to docker hub so we can get it tested before the PR is merged and also the final release is created ?

**Comment by joshblakeley** [comment]
> @joshblakeley @letzya it is possible for you guys to push a release candidate to docker hub so we can get it tested before the PR is merged and also the final release is created ?
> 
> This will also allow to issue opaque tokens via "passthrough" (not only SSO to the Dashboard) ?
> This ones=> "GenerateTemporaryAuthToken - Will generate a Tyk standard access token for the user, can be delivered as a redirect fragment OR as a direct API response (JSON)"
> 
> Not sure also about this error:
> branch saml-provider
> 
> tyk-identity-broker git:(saml-provider) go get
> 
> # github.com/crewjam/httperr
> ../../crewjam/httperr/httperr.go:24:5: undefined: "errors".As
> ../../crewjam/httperr/httperr.go:46:5: undefined: "errors".As
> 
> # github.com/TykTechnologies/tyk-identity-broker/backends
> backends/redis.go:132:18: not enough arguments in call to db.Set
> have (string, interface {}, number)
> want (context.Context, string, interface {}, time.Duration)
> backends/redis.go:143:19: not enough arguments in call to db.Get
> have (string)
> want (context.Context, string)
> backends/redis.go:158:24: cannot use r.fixKey(key) (type string) as type context.Context in argument to db.Del:
> string does not implement context.Context (missing Deadline method)
> 
> master all ok:
> 
> ➜ tyk-identity-broker git:(master) go get
> ➜ tyk-identity-broker git:(master) go build
> ➜ tyk-identity-broker git:(master)

Hi Bruno

The errors look like typical Go modules stuff - what is your Go version? Also it could depend on vendored deps etc

This flow is just for the SSO use case - feel free to adapt it for the temp token gen case in the gateway if you need that too! I'm happy to get the team to review it for you.

**Comment by bmonteiro** [comment]
Hi @joshblakeley, 

I'm running go1.10.8 darwin/amd64. 
Any suggestions :) ?
Yes, once I can build the code or get a docker image I will create a profile.json for GenerateTemporaryAuthToken and test it out.

**Comment by joshblakeley** [comment]
> Hi @joshblakeley,
> 
> I'm running go1.10.8 darwin/amd64.
> Any suggestions :) ?
> Yes, once I can build the code or get a docker image I will create a profile.json for GenerateTemporaryAuthToken and test it out.

Thats quite an old go version i would move up to 1.12 at least as thats what we build against right now.

As far as doing the token gen piece its not quite that simple. There needs to be some code added to handle the flow so creating a profile for it wont work yet.

**Comment by bmonteiro** [comment]
> > Hi @joshblakeley,
> > I'm running go1.10.8 darwin/amd64.
> > Any suggestions :) ?
> > Yes, once I can build the code or get a docker image I will create a profile.json for GenerateTemporaryAuthToken and test it out.
> 
> Thats quite an old go version i would move up to 1.12 at least as thats what we build against right now.
> 
> As far as doing the token gen piece its not quite that simple. There needs to be some code added to handle the flow so creating a profile for it wont work yet.

got it, will check it out. thx!

**Comment by bmonteiro** [comment]
> > > Hi @joshblakeley,
> > > I'm running go1.10.8 darwin/amd64.
> > > Any suggestions :) ?
> > > Yes, once I can build the code or get a docker image I will create a profile.json for GenerateTemporaryAuthToken and test it out.
> > 
> > 
> > Thats quite an old go version i would move up to 1.12 at least as thats what we build against right now.
> > As far as doing the token gen piece its not quite that simple. There needs to be some code added to handle the flow so creating a profile for it wont work yet.
> 
> got it, will check it out. thx!

@joshblakeley Maybe I'm missing something ?

➜  tyk-identity-broker git:(saml-provider) go version
go version go1.12.17 darwin/amd64


➜  tyk-identity-broker git:(saml-provider) go get -u ./...
# github.com/crewjam/httperr
../../crewjam/httperr/httperr.go:24:5: undefined: "errors".As
../../crewjam/httperr/httperr.go:46:5: undefined: "errors".As
# github.com/TykTechnologies/tyk-identity-broker/backends
backends/redis.go:132:18: not enough arguments in call to db.Set
	have (string, interface {}, number)
	want (context.Context, string, interface {}, time.Duration)
backends/redis.go:143:19: not enough arguments in call to db.Get
	have (string)
	want (context.Context, string)
backends/redis.go:158:24: cannot use r.fixKey(key) (type string) as type context.Context in argument to db.Del:
	string does not implement context.Context (missing Deadline method)

➜  tyk-identity-broker git:(saml-provider)

**Comment by bmonteiro** [comment]
> > > > Hi @joshblakeley,
> > > > I'm running go1.10.8 darwin/amd64.
> > > > Any suggestions :) ?
> > > > Yes, once I can build the code or get a docker image I will create a profile.json for GenerateTemporaryAuthToken and test it out.
> > > 
> > > 
> > > Thats quite an old go version i would move up to 1.12 at least as thats what we build against right now.
> > > As far as doing the token gen piece its not quite that simple. There needs to be some code added to handle the flow so creating a profile for it wont work yet.
> > 
> > 
> > got it, will check it out. thx!
> 
> @joshblakeley Maybe I'm missing something ?
> 
> ➜ tyk-identity-broker git:(saml-provider) go version
> go version go1.12.17 darwin/amd64
> 
> ➜ tyk-identity-broker git:(saml-provider) go get -u ./...
> 
> # github.com/crewjam/httperr
> ../../crewjam/httperr/httperr.go:24:5: undefined: "errors".As
> ../../crewjam/httperr/httperr.go:46:5: undefined: "errors".As
> 
> # github.com/TykTechnologies/tyk-identity-broker/backends
> backends/redis.go:132:18: not enough arguments in call to db.Set
> have (string, interface {}, number)
> want (context.Context, string, interface {}, time.Duration)
> backends/redis.go:143:19: not enough arguments in call to db.Get
> have (string)
> want (context.Context, string)
> backends/redis.go:158:24: cannot use r.fixKey(key) (type string) as type context.Context in argument to db.Del:
> string does not implement context.Context (missing Deadline method)
> 
> ➜ tyk-identity-broker git:(saml-provider)

FYI, works with Go 1.14

➜  tyk-identity-broker git:(saml-provider) ✗ go1.14.4 build
➜  tyk-identity-broker git:(saml-provider) ✗

**Comment by joshblakeley** [comment]
@sredxny Do we have a merge and release date for this yet?

**Comment by joshblakeley** [comment]
@matiasinsaurralde did @bmonteiro commit c5e6fdc make it into master with this PR too?
